import { UnsignedByteType } from 'three';
import { sharpen } from 'three/addons/tsl/display/SharpenNode.js';
import {
  diffuseColor,
  mrt,
  normalView,
  output,
  vec4,
} from 'three/tsl';
import type { Node } from 'three/tsl';

type NostalgiaScenePass = {
  setMRT: (configuration: ReturnType<typeof mrt>) => unknown;
  getTextureNode: (name: string) => Node;
};

export interface NostalgiaGBuffer {
  color: Node;
  albedo: Node;
  normal: Node;
  depth: Node;
}

/**
 * Reproduce Nostalgia's gbuffers_terrain.fsh attachment layout with native
 * WebGPU MRT.
 *
 * Nostalgia's solid.fsh writes:
 *   colortex0 = sceneAlbedo
 *   colortex1 = encoded normal + lightmap/specular data
 *   colortex2 = material/parallax/emission data
 *
 * Three's PassNode lets us provide arbitrary TSL expressions as MRT outputs,
 * so these are real scene-derived attachments rather than copies of the
 * final beauty buffer.
 */
export function activateNostalgiaGBuffer(scenePass: NostalgiaScenePass): NostalgiaGBuffer {
  // Keep only the attachments consumed by the current WebGPU deferred adapter.
  // Three's MRT defaults to RGBA16F, so:
  //   output = 8 bytes/sample
  //   albedo = 4 bytes/sample (RGBA8)
  //   normal = 8 bytes/sample (RGBA16F)
  // Total = 20 bytes/sample, safely below the device limit of 32.
  //
  // Do not read aLight here. Voxel chunks have it, but other scene geometry
  // (particles, player meshes, sky, etc.) does not; an unconditional TSL
  // attribute would make every material pipeline fail to build.
  scenePass.setMRT(
    mrt({
      output,
      albedo: diffuseColor,
      normal: normalView,
    }),
  );

  scenePass.getTexture('albedo').type = UnsignedByteType;

  return {
    color: scenePass.getTextureNode('output'),
    albedo: scenePass.getTextureNode('albedo'),
    normal: scenePass.getTextureNode('normal'),
    depth: scenePass.getTextureNode('depth'),
  };
}

/**
 * First real deferred lighting stage.
 *
 * This consumes the actual Nostalgia-style albedo/normal G-buffer instead of
 * the already-lit beauty buffer. It is intentionally the WebGPU equivalent
 * of the core diffuse operation in deferred1.fsh; shadow/VPS filtering is
 * added in the following stage once the WebGPU shadow attachments are exposed.
 */
export function createNostalgiaDeferredLighting(
  albedo: Node,
  sceneNormal: Node,
  lightDirectionView: Node,
  lightStrength: Node,
  sunLight: import('three').DirectionalLight,
): Node {
  const normal = sceneNormal.xyz.normalize();
  const lightDir = lightDirectionView.normalize();
  const diffuse = normal.dot(lightDir).max(0.0);

  // Use Three.js's native WebGPU shadow node. This samples the DirectionalLight
  // shadow map generated by WebGPURenderer, so the deferred pass receives the
  // same dynamic sun/moon shadowing as the scene.
  const shadowFactor = shadow(sunLight).clamp(0.0, 1.0);

  // Keep a small sky contribution while attenuating only the direct component
  // with the actual shadow map.
  const direct = diffuse.mul(lightStrength).mul(0.9).mul(shadowFactor);
  const lighting = direct.add(0.10);

  // output is already a vec4 node; replace the alpha component without
  // relying on the TSL vec4 constructor at runtime.
  return albedo.mul(lighting);
}

/**
 * Nostalgia's final.fsh applies CAS with strength 0.5 to colortex0.
 */
export function createNostalgiaFinalOutput(sceneColor: Node): Node {
  return sharpen(sceneColor, 0.5, false);
}

export function isNostalgiaFinalSource(source: string): boolean {
  return /textureCAS\s*\(/.test(source) && /uniform\s+sampler2D\s+colortex0/.test(source);
}
